test

diff --git a/.jenkins/Jenkinsfile3 b/.jenkins/Jenkinsfile3
--- a/.jenkins/Jenkinsfile3
+++ b/.jenkins/Jenkinsfile3
@@ -32,16 +32,21 @@ node {
       echo 'build done'
     }
   }
-
-  stage('push new image to docker hub') {
-             withCredentials(credentialsId: 'docker-config',
-                                  variable: 'DOCKER_CONFIG') {
-            echo 'Pushing to Docker Hub'
-            container.push()
+  stage('Run Application') {
+    sh("docker rm -f nginx ||:")
+    sh("docker run --name nginx -d -p 8081:80 testapp:${env.BUILD_NUMBER} ||:") 
+  }
+  stage('Trigger test') {
+  try {
+     b = build(job: 'project2', propagate: true).result
+     if(b == 'FAILURE'){
+     echo "Build failed"
+     
+      }
+           }
+  catch(error) { 
+      echo "$error"
+      currentBuild.result = "FAILURE"  }
+      
 }
-}   
-
-
-
-
 }
